name: project-setup-test

on: [push]

jobs:
  
  initial-setup:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          make install
      - name: Lint with pylint
        run: |
          make lint
    

  
